name: Generate docs

on:
  push:
    branches: [ master ]
    paths:
      - doc/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt install libicu-dev libgumbo-dev
    - name: Build Plet
      run: make IMAGEMAGICK=0 STATIC_MD4C=1 all
    - name: Build docs
      working-directory: ./doc
      run: ../plet build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/dist
