name: Generate docs

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install libicu-dev libgumbo-dev libmd4c-html0-dev
    - name: Build Plet
      run: make IMAGEMAGICK=0 all
    - name: Build docs
      working-directory: ./doc
      run: ../plet build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/dist
