name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt install valgrind libicu-dev
    - name: Build and run tests
      run: make GUMBO=0 STATIC_MD4C=1 IMAGEMAGICK=0 test
